#!/bin/bash

# function to download any package
package_installer(){
    local package=$1
    echo "Installing $package... please wait..."
    echo " "
    sudo apt update -y
    sudo apt install -y $package
    echo "done installing $package"
}

# check and download pre-req when necessary
pre_req_download(){
    local package=unzip

    if which $package &> /dev/null;
    then
        echo "the package exists: unzip"
    else
        echo "the package does not exist: unzip"
        package_installer $package
    fi
}

# to confirm what needs to be done
what_action(){
    local name=aws
    if which aws &> /dev/null;
    then
        echo "the aws command already exists"
        aws sts get-caller-identity
        action="all is good"
    else
        echo "the aws command does not exist"
        action="install aws command"
    fi
}

# download and install aws cli
download_aws(){
    if [[ "$action" == "install aws command" ]]
    then
        #DOWNLOAD USING THE CURL COMMAND
        curl -s "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        
        # UNZIP USING THE UNZIP PACKAGE
        unzip awscliv2.zip

        # RUN THE INSTALLER
        sudo ./aws/install

        # VERIFY THE INSTALLER
        echo "aws has been installed..."
        aws --version
    elif [[ "$action" == "all is good" ]]
    then
        echo " "
    fi
}

# CONFIGURE THE INSTALLED AWS COMMAND
configure_aws(){
    echo "Would you like to configure your AWS CLI now?(y/n)"
    read -p ">> " response

    case $response in
        y)
            # CONFIGURE THE CLI
            aws configure
        ;;
        n)
            # WE ARE DONE
            echo "To configure later, use the command: "
        ;;
        *)
            echo "your response is not understandable"
            echo "To configure later, use the 'áws configure'command"
            ;;
    esac
}

# THE MAIN SCRIPT
pre_req_download
what_action
download_aws
configure_aws