#!/bin/bash

# A script that will ask for a number and print out a message depending on the value. 

read -p "Enter a number: " n

case $((n % 2)) in 
    0)
        echo "the number $n is even";;
    *)  
        echo "the number $n is odd";;
esac