#!/bin/bash

check_even () {
   local mod=2;

   if [ $(("$1" % 2)) -eq 0 ]; then 
      echo "the number $1 is even"
   else 
      echo "the number $1 is odd"
   fi

}

number=2344

check_even $number
echo $mod